name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build the Docker image
        run: |
          docker build -t anchalshivank99/mt-auth-service:latest .

      - name: Push the Docker image
        run: |
          docker push anchalshivank99/mt-auth-service:latest

#  deploy:
#    runs-on: ubuntu-latest
#    needs: build
#
#    steps:
#      - name: Check out the code
#        uses: actions/checkout@v2
#
#      - name: Debug SSH key (do not print private key!)
#        run: |
#          echo "${{secrets.SSH_PRIVATE_KEY}}" | head -n 10 # Show only the first 10 lines, never the full key
#
#
#      - name: Set up SSH key using ssh-agent
#        run: |
#          mkdir -p ~/.ssh
#          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
#          chmod 600 ~/.ssh/id_rsa
#          eval $(ssh-agent -s)
#          ssh-add ~/.ssh/id_rsa
#          ssh-keyscan -t rsa 34.133.145.146 >> ~/.ssh/known_hosts
#
#
#      - name: SSH into GCP VM and deploy
#        run: |
#          ssh -i ~/.ssh/id_rsa -T anchalshivank99@34.133.145.146 'sudo ./deploy_auth_service.sh'
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
